<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261008174200 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Align messenger table and index names with Doctrine metadata';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE IF NOT EXISTS messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IF NOT EXISTS IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');

        $this->addSql('ALTER INDEX IF EXISTS idx_report_photo_report_id RENAME TO IDX_3EAB83614BD2A4C0');
        $this->addSql('ALTER INDEX IF EXISTS idx_equipment_zone_id RENAME TO IDX_D338D5839F2C3FAB');
        $this->addSql('ALTER INDEX IF EXISTS uniq_report_reference RENAME TO UNIQ_C42F7784AEA34913');
        $this->addSql('ALTER INDEX IF EXISTS idx_report_status RENAME TO IDX_C42F77847B00651C');
        $this->addSql('ALTER INDEX IF EXISTS idx_report_priority RENAME TO IDX_C42F778462A6DC27');
        $this->addSql('ALTER INDEX IF EXISTS idx_report_created_at RENAME TO IDX_C42F77848B8E8428');
        $this->addSql('ALTER INDEX IF EXISTS idx_report_zone_id RENAME TO IDX_C42F77849F2C3FAB');
        $this->addSql('ALTER INDEX IF EXISTS idx_report_author_id RENAME TO IDX_C42F7784F675F31B');
        $this->addSql('ALTER INDEX IF EXISTS idx_report_assigned_to_id RENAME TO IDX_C42F7784F4BD7827');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS messenger_messages');

        $this->addSql('ALTER INDEX IF EXISTS IDX_3EAB83614BD2A4C0 RENAME TO idx_report_photo_report_id');
        $this->addSql('ALTER INDEX IF EXISTS IDX_D338D5839F2C3FAB RENAME TO idx_equipment_zone_id');
        $this->addSql('ALTER INDEX IF EXISTS UNIQ_C42F7784AEA34913 RENAME TO uniq_report_reference');
        $this->addSql('ALTER INDEX IF EXISTS IDX_C42F77847B00651C RENAME TO idx_report_status');
        $this->addSql('ALTER INDEX IF EXISTS IDX_C42F778462A6DC27 RENAME TO idx_report_priority');
        $this->addSql('ALTER INDEX IF EXISTS IDX_C42F77848B8E8428 RENAME TO idx_report_created_at');
        $this->addSql('ALTER INDEX IF EXISTS IDX_C42F77849F2C3FAB RENAME TO idx_report_zone_id');
        $this->addSql('ALTER INDEX IF EXISTS IDX_C42F7784F675F31B RENAME TO idx_report_author_id');
        $this->addSql('ALTER INDEX IF EXISTS IDX_C42F7784F4BD7827 RENAME TO idx_report_assigned_to_id');
    }
}

